package fopscaddyrouter

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
)

func GenerateCaddyfile(registry Registry) ([]byte, error) {
	if err := validateRegistry(registry); err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by fops-caddy-router. Do not edit manually.\n\n")

	keys := make([]string, 0, len(registry.Stacks))
	for key := range registry.Stacks {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	for _, key := range keys {
		stack := registry.Stacks[key]
		routes := append([]Route(nil), stack.Routes...)
		sort.SliceStable(routes, func(i, j int) bool {
			return routes[i].ID < routes[j].ID
		})

		for _, route := range routes {
			entrypoint := route.Entrypoint
			if entrypoint == "" {
				entrypoint = defaultEntrypoint(stack, route)
			}
			hosts := append([]string(nil), route.Hosts...)
			sort.Strings(hosts)

			fmt.Fprintf(&buf, "%s {\n", strings.Join(hosts, ", "))
			fmt.Fprintf(&buf, "\timport /etc/fops-router/entrypoint.Caddyfile %s\n\n", entrypoint)
			fmt.Fprintf(&buf, "\treverse_proxy %s://%s:%d {\n", route.Upstream.Scheme, route.Upstream.NetworkAlias, route.Upstream.Port)
			if route.Upstream.Scheme == "https" {
				buf.WriteString("\t\ttransport http {\n")
				buf.WriteString("\t\t\ttls\n")
				tlsServerName := route.Upstream.TLSServerName
				if tlsServerName == "" {
					tlsServerName = hosts[0]
				}
				fmt.Fprintf(&buf, "\t\t\ttls_server_name %s\n", tlsServerName)
				if route.Upstream.TLSInsecureSkipVerify {
					buf.WriteString("\t\t\ttls_insecure_skip_verify\n")
				}
				buf.WriteString("\t\t}\n")
			}
			buf.WriteString("\t\theader_up Host {host}\n")
			buf.WriteString("\t\theader_up X-Real-IP {remote_host}\n")
			buf.WriteString("\t\theader_up X-Original-URI {uri}\n")
			buf.WriteString("\t\theader_up X-Original-Query {query}\n")
			buf.WriteString("\t\theader_up X-Forwarded-Proto https\n")
			buf.WriteString("\t\theader_up X-Forwarded-Port 443\n")
			buf.WriteString("\t}\n")
			buf.WriteString("}\n\n")
		}
	}

	return buf.Bytes(), nil
}

func defaultEntrypoint(stack Stack, route Route) string {
	return stack.Project + "-" + stack.Instance + "-" + route.ID
}
