name: fops-router

on:
  push:
    branches: ["main"]
    paths:
      - "fops-router/**"
      - ".github/workflows/_docker-image.yml"
      - ".github/workflows/fops-router.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "fops-router/**"
      - ".github/workflows/_docker-image.yml"
      - ".github/workflows/fops-router.yml"

concurrency:
  group: fops-router-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fops-router/plugins/fops-caddy-router
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v6
        with:
          go-version: "1.25"
          cache-dependency-path: fops-router/plugins/fops-caddy-router/go.sum

      - name: Run unit tests
        run: go test ./...

  build:
    needs: test
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      security-events: write
    uses: ./.github/workflows/_docker-image.yml
    with:
      image: fops-router
      version: "2.11.3"
      fops-image-version: "2.11.3"
      context: ./fops-router
      dockerfile: ./fops-router/Dockerfile
      trivy-category: trivy-fops-router
